spring:
  dubbo:
    application:
      id: dubbo-provider
      name: dubbo-provider
    registry:
      address: zookeeper://localhost:2181
    server: true
    protocol:
      name: dubbo
      port: 20880
