server:
  port: 8888

spring:
  dubbo:
    application:
      id: dubbo-consumer
      name: dubbo-consumer
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20889
